name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies (test-only fast)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt
      # Optional: to run full install (including selenium), set an environment variable in the workflow dispatch or matrix
      - name: Optional full install
        if: env.FULL_INSTALL == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest -q
